//
//  challenge2.cpp
//  ProgChallengeC++
//
//  Created by home on 1/7/19.
//  Copyright © 2019 jorgemichaeljones. All rights reserved.
//
/*
 
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
#include <iostream>
using namespace std;
void printFibSeq(int n);
void printFibSeqs(int n){
    int num = 1;
  //  int temp = n;
    while(num > 40){
        num = num + num;
        cout << num << endl;
    }
}
